In [1]:
#Creating Array

In [2]:
import numpy as np

x = [1,2,3,4]
y=np.array(x)
y

array([1, 2, 3, 4])

In [3]:
#MultiDimensional Arrays

In [4]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y.ndim)
y

2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
y = np.array([1,2,3],ndmin=6)
print(y.ndim)
y

6


array([[[[[[1, 2, 3]]]]]])

In [1]:
# Specific Types of Arrays

In [9]:
#Zeros array
arr_zeros = np.zeros(4)
arr_zeros_4x3 = np.zeros((4,3))
print(arr_zeros)
print(arr_zeros_4x3)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Ones array
arr_ones = np.ones(4)
arr_ones_4x3 = np.ones((4,3))
print(arr_ones)
print(arr_ones_4x3)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Empty array
arr_empty = np.empty(4)
arr_empty_4x3 = np.empty((4,3))
print(arr_empty)
print(arr_empty_4x3)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#Range array
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [14]:
#Diagonal array
arr_dg = np.eye(4)
print(arr_dg)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#Linespace array
arr_ln = np.linspace(0,20, num=5)
print(arr_ln)

[ 0.  5. 10. 15. 20.]


In [19]:
#Array of Random Number

In [21]:
arr_rand = np.random.rand(4)
arr_rand_multi_d = np.random.rand(2,5)
print(arr_rand)
print(arr_rand_multi_d)

[0.27555106 0.21235206 0.03530096 0.61824614]
[[0.08158975 0.79754584 0.04414001 0.44315378 0.8516251 ]
 [0.42906262 0.37502557 0.52982046 0.44456275 0.45703067]]


In [22]:
#Array of Random Number with Randn
arr_randn = np.random.randn(4)
print(arr_randn)

[ 0.39451308  0.33214465 -1.99837155  0.1588634 ]


In [25]:
#Array of Random Number with Ranf
arr_ranf = np.random.ranf(4)
print(arr_ranf)

[0.42023449 0.15364741 0.03488176 0.20173395]


In [28]:
#Array of Random Number with Randint
#np.random.randint(min,max,n)
arr_randi = np.random.randint(5,20,5)
print(arr_randi)

[14 17  5 19  6]


In [29]:
#WORKING WITH DATA TYPES IN NUMPY

In [30]:
#Integer
var = np.array([1,2,4,8,16,32])
print("Data Type:",var.dtype)

Data Type: int32


In [33]:
#Float
var2 = np.array([1.0,2.0,4.0,8.0,16.0,32.0])
print("Data Type:",var2.dtype)

Data Type: float64


In [37]:
#String and mixed
var3 = np.array(["a","b","c","d"])
var4 = np.array(["a","b","c","d",16,32.0])
print("Data Type:",var3.dtype)
print("Data Type:",var4.dtype)

Data Type: <U1
Data Type: <U32


In [46]:
#INT 32 ti INT 8
var5 = np.array([100,200,400,800,1000], dtype= np.int8)
print("Data Type:",var2.dtype)
print(var5)

Data Type: int8
[ 100  -56 -112   32  -24]


In [45]:
#INT 32 ti FLOAT
var6 = np.array([100,200,400,800,1000], dtype= "float")
print("Data Type:",var2.dtype)
print(var6)

Data Type: int8
[ 100.  200.  400.  800. 1000.]


In [48]:
var7 = np.array([100,200,400,800,1000], dtype= "float")
new = np.float32(var7)
anew = np.int_(new)
print("Data Type:",var7.dtype,var7)
print("Data Type:",new.dtype,new)
print("Data Type:",anew.dtype,anew)

Data Type: float64 [ 100.  200.  400.  800. 1000.]
Data Type: float32 [ 100.  200.  400.  800. 1000.]
Data Type: int32 [ 100  200  400  800 1000]


In [51]:
var8 = np.array([100,200,400,800,1000], dtype= "float")
bnew = var8.astype(int)

print("Data Type:",var8.dtype,var8)
print("Data Type:",var8.dtype,bnew)

Data Type: float64 [ 100.  200.  400.  800. 1000.]
Data Type: float64 [ 100  200  400  800 1000]


In [52]:
#Arthemic Operations in Numpy

In [57]:
avar = np.array([2,4,6,8,16])
print(avar+2)
print(avar-2)
print(avar*2)
print(avar/2)

[ 4  6  8 10 18]
[ 0  2  4  6 14]
[ 4  8 12 16 32]
[1. 2. 3. 4. 8.]
[ 3  7 11 15 25]


In [58]:
avar2 = np.array([1,3,5,7,9])
avar3 = avar + avar2
print(avar3)

[ 3  7 11 15 25]


In [59]:
print("11/10/2024")

11/10/2024


In [60]:
#Array Operations

In [61]:
ar = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [63]:
#Transpose
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [66]:
#flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [70]:
#1D max, min, sort with arg
oneD_arr = np.array([12,4,655,23])
print(oneD_arr.argmax())
print(oneD_arr.argmin())
print(oneD_arr.argsort())

2
1
[1 0 3 2]


In [71]:
#2D max, min, sort with arg
print(ar.argmax())
print(ar.argmin())
print(ar.argsort())

8
0
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [74]:
#2D max, min, sort with arg with axes
print(ar.argmax(axis=0))
print(ar.argmin(axis=0))
print(ar.argsort(axis=0))

[2 2 2]
[0 0 0]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [86]:
#reshape
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
#Search, max, min
print(ar)
print(ar.max())
print(ar.min())
print(np.where(ar>5))
print(np.count_nonzero(ar))
print(np.nonzero(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))
9
(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [98]:
#To list
print(ar.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [101]:
#Slicing
print(ar[0:2,0:2])

[[1 2]
 [4 5]]


In [8]:
#Loading CSV as an Array
#Loading

data = np.genfromtxt(
    'data.csv',           
    delimiter=",",                
    dtype=None,                   
    encoding='utf-8',             
    names=None,                   
    missing_values='',            
    filling_values=np.nan,   
    invalid_raise = False #To ignore rows with inconsistant column count
)

In [9]:
print(data[:5])  # Header Display
print(data.shape)

[['Head1' 'Head2' 'Head3' 'Head4' 'Head5']
 ['22' 'ab' '5t' '1100' 'adf']
 ['32' 'ac' '6y' '2122' 'dsgf']
 ['44' 'af' '5q' '2344' 'dsaf']
 ['12' 'lk' '6k' '4343' 'knkk']]
(6, 5)
