In [2]:
#Creating Array

In [3]:
import numpy as np

x = [1,2,3,4]
y=np.array(x)
y

array([1, 2, 3, 4])

In [6]:
#MultiDimensional Arrays

In [4]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y.ndim)
y

2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
y = np.array([1,2,3],ndmin=6)
print(y.ndim)
y

6


array([[[[[[1, 2, 3]]]]]])

In [1]:
# Specific Types of Arrays

In [9]:
#Zeros array
arr_zeros = np.zeros(4)
arr_zeros_4x3 = np.zeros((4,3))
print(arr_zeros)
print(arr_zeros_4x3)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Ones array
arr_ones = np.ones(4)
arr_ones_4x3 = np.ones((4,3))
print(arr_ones)
print(arr_ones_4x3)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Empty array
arr_empty = np.empty(4)
arr_empty_4x3 = np.empty((4,3))
print(arr_empty)
print(arr_empty_4x3)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#Range array
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [14]:
#Diagonal array
arr_dg = np.eye(4)
print(arr_dg)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#Linespace array
arr_ln = np.linspace(0,20, num=5)
print(arr_ln)

[ 0.  5. 10. 15. 20.]
